//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CentreInformatique
{
    #region Proprietes
    public virtual int num_centre
	{
		get;
		set;
	}

	public virtual string adresse_centre
	{
		get;
		set;
	}

	public virtual string cpl_centre
	{
		get;
		set;
	}

	public virtual string ville_centre
	{
		get;
		set;
	}

	public virtual string tel_centre
	{
		get;
		set;
	}

	public virtual Contrat Contrat
	{
		get;
		set;
	}
    
    public int NumCont { get; set; }

	//public virtual Client Client
	//{
	//	get;
	//	set;
	//}

    public int NumCli { get; set; }

    #endregion

    #region Constructeur

    public CentreInformatique() { }

    public CentreInformatique(int numceinfo, string adrceinfo, string cpceinfo, string vilceinfo, string telceinfo,
            int clceinfo)
    {
        num_centre = numceinfo;
        adresse_centre = adrceinfo;
        cpl_centre = cpceinfo;
        ville_centre = vilceinfo;
        tel_centre = telceinfo;
        NumCli = clceinfo;
    }
    #endregion Constructeurs
    
    #region Méthodes
    public override string ToString()
    {
        return string.Format("Centre : {0}, Client : {1}, Adresse : {2}, Ville : {3}",
            num_centre, NumCli, adresse_centre, ville_centre);
    }

    public override bool Equals(object cti1)
    {
        if (cti1 is CentreInformatique)
            return
                ((CentreInformatique)cti1).num_centre.Equals(this.num_centre);
        else
            return false;
    }
    #endregion
}

