//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CentreInformatique
{
	public virtual int num_centre
	{
		get;
		set;
	}

	public virtual string adresse_centre
	{
		get;
		set;
	}

	public virtual char cpl_centre
	{
		get;
		set;
	}

	public virtual string ville_centre
	{
		get;
		set;
	}

	public virtual string tel_centre
	{
		get;
		set;
	}

	public virtual Contrat Contrat
	{
		get;
		set;
	}

	public virtual Client Client
	{
		get;
		set;
	}

}

