//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Client
{
	public virtual int num_client
	{
		get;
		set;
	}

	public virtual string nom_client
	{
		get;
		set;
	}

	public virtual string adresse_client
	{
		get;
		set;
	}

	public virtual char cp_client
	{
		get;
		set;
	}

	public virtual string ville_client
	{
		get;
		set;
	}

	public virtual string tel_client
	{
		get;
		set;
	}

}

