//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Contrat
{
	public virtual int num_contrat
	{
		get;
		set;
	}

	public virtual decimal montant_contrat
	{
		get;
		set;
	}

	public virtual DateTime date_validite_contrat
	{
		get;
		set;
	}

	public virtual DateTime date_echeance_contrat
	{
		get;
		set;
	}

	public virtual DateTime date_resiliation_contrat
	{
		get;
		set;
	}

	public virtual string commentaire_contrat
	{
		get;
		set;
	}

	public virtual sbyte statut
	{
		get;
		set;
	}

	public virtual Client Client
	{
		get;
		set;
	}

}

